export const statusColors = {
    "status-normal": "#009DE4",
    "status-normal-soft": "#E6F7FF",
    "status-normal-text": "#03587F",
    "status-normal-border": "#8AD9FD",
    "status-warning": "#E08600",
    "status-warning-soft": "#FFF4E2",
    "status-warning-text": "#8F5500",
    "status-warning-border": "#F8D399",
    "status-offline": "#6B7177",
    "status-offline-soft": "#EEF0F1",
    "status-offline-text": "#474C51",
    "status-offline-border": "#CDD1D4",
    "status-fault": "#D92D20",
    "status-fault-soft": "#FDECEA",
    "status-fault-text": "#9E1B12",
    "status-fault-border": "#F4B5AE",
    "status-anomaly": "#8B5CF6",
    "status-anomaly-soft": "#F1EAFE",
    "status-anomaly-text": "#5B21B6",
    "status-anomaly-border": "#C9B2FA",
};
