export type Tier = 'routine' | 'significant' | 'emergency';
export type Outcome = 'green' | 'yellow' | 'red';
export type Contact = { name: string; relationship: string; phone: string; nearby: boolean };
export type Profile = {
  id: string;
  name: string;
  preferred_name: string;
  phone: string;
  timezone: string;
  call_time: string;
  medicine: string;
  medicine_time: string;
  language: 'en-US';
  contacts: Contact[];
  consent: 'pending' | 'granted' | 'declined';
  consent_words: string | null;
  consent_at: string | null;
  owner_id: string;
  enrolled: boolean;
};
export type Alert = {
  actual_fall?: boolean | null;
  id: string;
  incident_id: string;
  concern: string;
  tier: Tier | null;
  assessment: 'pending' | 'complete';
  quote: string | null;
  reason: string;
  created_at: string;
  handled_at: string | null;
  notification_status: string;
  subject: 'elder' | 'other';
  checkin_id?: string;
  call_state?: string;
  local_date?: string;
};
export type Leg = {
  id: string;
  kind: string;
  state: string;
  started_at: string;
  ended_at: string | null;
};
export type CheckIn = {
  id: string;
  elder_id: string;
  local_date: string;
  created_at: string;
  ended_at: string | null;
  state: string;
  mode: string;
  complete: boolean;
  medicine_result: 'taken' | 'not_taken' | 'unknown';
  medicine_due: boolean | null;
  alerts: Alert[];
  legs: Leg[];
  retry_at: string | null;
  transcript: { speaker: string; text: string; at: string }[];
  summary: string | null;
  text_expired: boolean;
  day_status: Outcome;
  answers: Record<string, string>;
  family: string[];
  family_joined_at: string | null;
  active_question: string | null;
  farewell_asked: boolean;
};
export type Dashboard = {
  mode: string;
  profile: Profile | null;
  profiles: Profile[];
  checkins: CheckIn[];
  alerts: Alert[];
};
